version: "3.8"

services:
  api-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - JWT_KEY=${JWT_KEY}
      - DATABASE_URL=${DATABASE_URL}
