name: CD - Studentblog Frontend

on:
    push:
      branches:
        - main
      paths:
        - 'frontend/**'
        - '!**/*.md'
    workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'

      - name: Build and push Docker image to Artifact Registry
        run: |
          gcloud builds submit ./frontend \
          --config=./frontend/cloudbuild.yaml \
          --gcs-source-staging-dir=gs://${{ secrets.GCP_PROJECT_ID }}_cloudbuild/source \
          --project=${{ secrets.GCP_PROJECT_ID }}
        env:
          PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          
      - name: 'Deploy to Cloud Run'
        run: |
          gcloud run deploy studentblog-frontend \
          --image europe-west2-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/studentblog-frontend-repo/studentblog-frontend:latest \
          --region europe-west2 \
          --allow-unauthenticated \
          --project ${{ secrets.GCP_PROJECT_ID }} \
          --max-instances=4
