name: ci-backend

on:
  push:
    paths:
      - "backend/**"
    branches:
      - main  
  pull_request:
    paths:
      - "backend/**"
    branches:
      - main
  workflow_dispatch:


jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.0.307' 
      
      - name: Restore dependencies
        run: dotnet restore ./StudentBlogApi.sln
      
      - name: Build
        run: dotnet build ./StudentBlogApi.sln --configuration Release --no-restore
      
      - name: Test
        run: dotnet test ./StudentBlogApi.sln --configuration Release --no-build
