name: ci-backend

on:
  push:
    branches:
      - '**'
      - '!main'
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.0.307' 
      
      - name: Restore dependencies
        run: dotnet restore ./Backend/StudentBlogApi.sln
      
      - name: Build
        run: dotnet build ./Backend/StudentBlogApi.sln --configuration Release --no-restore
      
      - name: Test
        run: dotnet test ./Backend/StudentBlogApi.sln --configuration Release --no-build
