name: CI - StudentBlog Backend

on:
  push:
    paths:
      - "backend/**"
    branches:
      - main  
  pull_request:
    paths:
      - "backend/**"
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.0.x'
      
      - name: Clean
        run: dotnet clean ./StudentBlogAPI.sln --configuration Release
      
      - name: Restore dependencies
        run: dotnet restore ./StudentBlogAPI.sln
      
      - name: Build
        run: dotnet build ./StudentBlogAPI.sln --configuration Release --no-restore
      
      - name: Test
        run: dotnet test ./StudentBlogAPI.sln --configuration Release --no-build --logger "trx;LogFileName=test_results.xml" --results-directory ./TestResults
      
      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: Test Results
          path: ./TestResults/*.xml
